# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '190618FirebaseLoginExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 190618FirebaseLoginExample
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end
