# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '190603APIMoviePractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 190603APIMoviePractice
  pod 'Alamofire', '~>5.0.0-beta.5'
end
